# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lss.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'lss.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlss.proto\x12\x03lss\"Z\n\x05Image\x12\x11\n\tcamera_id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x11\n\ttimestamp\x18\x05 \x01(\x01\":\n\nDroneInput\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\x05\x12\x1a\n\x06images\x18\x02 \x03(\x0b\x32\n.lss.Image\"-\n\nLSSRequest\x12\x1f\n\x06\x64rones\x18\x01 \x03(\x0b\x32\x0f.lss.DroneInput\"M\n\x08Neighbor\x12\x13\n\x0bneighbor_id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\x12\x0b\n\x03yaw\x18\x05 \x01(\x02\"A\n\x0b\x44roneResult\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\x05\x12 \n\tneighbors\x18\x02 \x03(\x0b\x32\r.lss.Neighbor\"0\n\x0bLSSResponse\x12!\n\x07results\x18\x01 \x03(\x0b\x32\x10.lss.DroneResult28\n\nLSSService\x12*\n\x05Infer\x12\x0f.lss.LSSRequest\x1a\x10.lss.LSSResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lss_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGE']._serialized_start=18
  _globals['_IMAGE']._serialized_end=108
  _globals['_DRONEINPUT']._serialized_start=110
  _globals['_DRONEINPUT']._serialized_end=168
  _globals['_LSSREQUEST']._serialized_start=170
  _globals['_LSSREQUEST']._serialized_end=215
  _globals['_NEIGHBOR']._serialized_start=217
  _globals['_NEIGHBOR']._serialized_end=294
  _globals['_DRONERESULT']._serialized_start=296
  _globals['_DRONERESULT']._serialized_end=361
  _globals['_LSSRESPONSE']._serialized_start=363
  _globals['_LSSRESPONSE']._serialized_end=411
  _globals['_LSSSERVICE']._serialized_start=413
  _globals['_LSSSERVICE']._serialized_end=469
# @@protoc_insertion_point(module_scope)
